### ISSUE TITLE
Can we install a Symphony app without Composer?

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursInstaller#14]
@damirius I'd like your insight about the question because I'm not sure we can install composer on shared hosting. 

Thanks

**Comment by damirius** [comment]
@WebDevJL 

Well we can in theory deploy it on local machine then compress it upload it and unpack it on the server. That will take of course huge amount of time to do especially if we want to have 2 QA domains and 1 codereview domain. It would be better to move back to c9 then to do this honestly and leave that hosting for production only so we don't have to do that often. I know I'm totally boring with this but if we are going with hosting which is 12 euro per month we could find better VPSes which are even cheaper than that.

**Comment by WebDevJL** [comment]
@damirius I think I have convinced the client to keep LiquidWeb for now to avoid work that would only save the hosting fee. We have made a procedure that works well and he prefers to keep that.

Thanks.
