### ISSUE TITLE
Release latest version on Prod deployment 

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/TrekToursInstaller#19]
**_Edited**_

Cc: @over-e

To: @damirius 

We have a final domain! 
It is ebikemontblanc.com

I have done the following :
- created a new cpanel user : ebikemontblanc 
- installed the applications under the cpanel user's /home/ebikemontblanc/public_html/sites folder 
- setup the Google analytics and reCaptcha for ebikemontblanc.com domain 

What's left to do is:
- [x] modify the httpd.conf file to make apache point http://ebikemontblanc.com to /home/ebikemontblanc/public_html/sites/public folder. **_Try not to modify the httpd.conf as it is recommended**_
- [x] modify the httpd.conf file to make apache point http://api.ebikemontblanc.com subdomain to /home/ebikemontblanc/public_html/sites/api. **_Try not to modify the httpd.conf as it is recommended**_
- [x] the flyer URL must be up at http://ebikemontblanc.com/
- [x] configuration of the API subdomain as http://api.ebikemontblanc.com doesn't work at the moment 
- [x] rewrite the URL of flyer so that we have just to enter http://ebikemontblanc.com without the "web" the suffix
- [x] setup the API url to http://api.ebikemontblanc.com so the suffix "web" is rewritten as well.

Can you please take care of this? 

Please provide me with the details of updates so we can both repeat it later on. 

Thanks.

**Comment by WebDevJL** [comment]
@damirius 

PS: I have setup the API url in the Flyer to http://api.ebikemontblanc.com so the suffix "web" should be rewritten as well.

**Comment by WebDevJL** [comment]
@damirius 

I saw that, while editing the httpd.conf, it is saying not to modify the file and use aliases conf instead. 
So I reverted to the previous configuration. I made a copy of the httpd.conf file I altered (see /etc/apache2/conf/httpd.conf.modified.jli).

So I will update the tasks list above accordingly to that change.

**Comment by damirius** [comment]
@WebDevJL 

Adding subdomain just doesn't work. I've tried removing it and adding it again and also I played around with dns editor. Can you tell me if everything is forwarded to our nameservers from registar nameserver for that domain?

Also, I've pointed flyer domain correctly to the web directory

**Comment by WebDevJL** [comment]
@damirius

Here is the screenshot sent by Stéphane of the OVH setup.

Should he create the subdomain api.ebikemontblanc.com ?

![image](https://cloud.githubusercontent.com/assets/3506074/18313164/91a8056a-750d-11e6-9241-fa533cd7addc.png)

**Comment by WebDevJL** [comment]
@damirius

Here is the screenshot sent by Stéphane of the OVH setup.

As far as I know, he has not created a subdomain. Should he?

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com

**Comment by damirius** [comment]
@WebDevJL 

Let's try with adding api.ebikemontblanc.com there too.
Don't know if it's because dns propagation or not

**Comment by WebDevJL** [comment]
to: @over-e
cc: @damirius

Stéphane,

Can you add a subdomain on OVH and make the Record A or "Cible" point to
the LiquidWeb server IP just the raw domain?
Let us know when it is done.

Thanks.

## 

Jérémie Litzer
CEO @ _Puzzlout_ http://puzzlout.com

**Comment by over-e** [comment]
Ok
It's done

[image: Inline images 1]

**Comment by damirius** [comment]
@WebDevJL 

It seems to work now http://api.ebikemontblanc.com/doc

**Comment by WebDevJL** [comment]
@damirius @over-e 

Awesome team work! We are now live :)

@damirius : we are making progress with the design. The first mockup draft is in tonight. Stay tuned.
